### ISSUE TITLE
Cannot launch Discord due to 5 segmentation fault

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.discordapp.Discord#141]
I use Fedora 34 Silverblue on both my desktop and laptop. Discord works fine on my laptop whereas on my desktop it suddenly stopped working.

Here is the error when I launch Discord on my desktop:

```bash
TheEvilSkeleton@TheMainDesktop ~> flatpak run com.discordapp.Discord
Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.8/site-packages/Xlib/protocol/display.py", line 85, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/app/lib/python3.8/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/app/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 61, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
Discord 0.0.13
(node:5) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Failed to generate minidump.[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
/app/bin/discord: line 9:     5 Segmentation fault      (core dumped) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord "$@"
```

This also happens when I try to launch `com.discordapp.DiscordCanary`.

**Comment by TheEvilSkeleton** [comment]
Creating a new issue fixed the issue, but I prefer fixing the issue because I do not want to transfer files, etc.
