### ISSUE TITLE
PRC No longer working for me

### ISSUE THREAD

**Issue by Taiko2k** [flathub/com.discordapp.Discord#200]
My Flatpaked app used to work with PRC, but now doesn't for some reason. (Neither with Flatpak Discord or Native)

I use the Python library PyPresence and get this error regardless if Discord is running or not.

```
ipc_path: /run/user/1000/discord-ipc-9

Exception in thread Thread-12:
Traceback (most recent call last):


  File "/app/bin/t_modules/t_main.py", line 21822, in discord_loop
pa: Connect pulse
    RPC.connect()
  File "/app/lib/python3.9/site-packages/pypresence/presence.py", line 45, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/lib/python3.9/site-packages/pypresence/baseclient.py", line 107, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path)
  File "/usr/lib/python3.9/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
``` 

I wasn't sure if to post this issue here or on [PyPresence](https://github.com/qwertyquerty/pypresence), but it does work normally without Flatpak. Could there be something I'm missing or should I open an issue on PyPresence?

**Comment by gasinvein** [comment]
I guess this is about `com.github.taiko2k.tauonmb` app. This issue doesn't seem to happen for me. What's the exact version where it's reproducible?

**Comment by Taiko2k** [comment]
@gasinvein Yes that's the app. I figured out it's related to the version of pypresence used. 

It's working now because I downgraded the version of pypresence used in the manifest to 4.0.0. But all later versions including the latest of it seem to have the issue.

**Comment by gasinvein** [comment]
Is the build from flathub/com.github.taiko2k.tauonmb@afec909594e91bcfa62084706f004911cb4a218e expected to be broken (it works for me, too)?

**Comment by Taiko2k** [comment]
Yes I would expect that build not to work. I did have a number of users reporting it wasn't working so it wasn't just me. I'm not sure why it would be working now.

**Comment by gasinvein** [comment]
Can you please submit a known-broken build somewhere? E.g. open a dummy PR with with your recent fix reverted, so we can get a test build.

**Comment by Taiko2k** [comment]
Okay test build here https://github.com/flathub/com.github.taiko2k.tauonmb/pull/3

In order to test, run the app and you'll need to import and start playing an audio file before it will attempt to connect use discord rp. But first, to enable discord support, you need to click "MENU" > "Settings...", (then with the "function" tab still selected) select page 4. There there is a checkbox labelled "Enable Discord Rich Presence".

Below that checkbox is some status text, once a audio track is playing; if its working it will say "Status: Connected". When its not working it will say "Status: Discord not found?".

An error wont show in the terminal, but if you want try debug, being python you can directly modify the python files installed by flatpak. The code that handles discord rp in Tauon Music Box is in `bin/t_modules/t_main.py`, do a search in that file for the text `Discord not running?`, that will take you to where the related code is. For example, above that line you can add a `raise` command to see the traceback error.

**Comment by gasinvein** [comment]
Thanks. It seems to work properly if I bypass the wrapper, removing leftover socket symlinks (`rm -v $XDG_RUNTIME_DIR/discord-*`), and run the app directly (`python3 /app/bin/tauon.py`).
I'm not entirely sure how exactly the wrapper breaks RP, but since PyPresence 4.1.0+ is supposed to support flatpak'ed Discord natively, I believe the symlink creation can be dropped anyway.

**Comment by Taiko2k** [comment]
Yep I can confirm removing the wrapper fixes it for me too, both with Flatpak Discord and external Discord. This can be closed now.
