### ISSUE TITLE
set-gtk-dark-theme.py errors on Wayland

### ISSUE THREAD

**Issue by neerajlohia** [flathub/com.discordapp.Discord#208]
## Description
Discord crashes on startup. A small Discord window of 'starting up' / 'updated' opens, followed a bigger window without decorations. These windows open and close quickly few times until the flatpak finally exits. 
I am running Discord with command: 
`flatpak run --socket=wayland com.discordapp.Discord --enable-features=UseOzonePlatform --ozone-platform=wayland`
#### Output:
```
F: Filesystem suffix "ro" is not applicable for --nofilesystem
F: Filesystem suffix "ro" is not applicable for --nofilesystem
Disabled updates
[6 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/discord/Discord --type=zygote
F: Filesystem suffix "ro" is not applicable for --nofilesystem
F: Filesystem suffix "ro" is not applicable for --nofilesystem
Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.9/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
Discord 0.0.17
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: disabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/neeraj/.var/app/com.discordapp.Discord/config/discord/0.0.17/modules
[Modules] Module installed file path: /home/neeraj/.var/app/com.discordapp.Discord/config/discord/0.0.17/modules/installed.json
[Modules] Module download path: /home/neeraj/.var/app/com.discordapp.Discord/config/discord/0.0.17/modules/pending
[Modules] No updates to install
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
[Modules] No module updates available.
Module ./ElectronTestRpc was not included.
Cannot upload crash dump: failed to open
--2022-03-12 17:48:02--  https://sentry.io/api/146342/minidump/?sentry_key=384ce4413de74fe0be270abe03b2b35a
Resolving sentry.io (sentry.io)... 35.188.42.15
Connecting to sentry.io (sentry.io)|35.188.42.15|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-03-12 17:48:03 ERROR 400: Bad Request.


Unexpected crash report id length
Failed to get crash dump id.
Report Id:
[WebContents] crashed (reason: crashed, exitCode: 139)... reloading
Module ./ElectronTestRpc was not included.
Cannot upload crash dump: failed to open
--2022-03-12 17:48:05--  https://sentry.io/api/146342/minidump/?sentry_key=384ce4413de74fe0be270abe03b2b35a
Resolving sentry.io (sentry.io)... 35.188.42.15
Connecting to sentry.io (sentry.io)|35.188.42.15|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-03-12 17:48:07 ERROR 400: Bad Request.


Unexpected crash report id length
Failed to get crash dump id.
Report Id:
[WebContents] crashed (reason: crashed, exitCode: 139)... reloading
Module ./ElectronTestRpc was not included.
Cannot upload crash dump: failed to open
--2022-03-12 17:48:10--  https://sentry.io/api/146342/minidump/?sentry_key=384ce4413de74fe0be270abe03b2b35a
Resolving sentry.io (sentry.io)... 35.188.42.15
Connecting to sentry.io (sentry.io)|35.188.42.15|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-03-12 17:48:12 ERROR 400: Bad Request.


Unexpected crash report id length
Failed to get crash dump id.
Report Id:
[WebContents] crashed (reason: crashed, exitCode: 139)... reloading
Module ./ElectronTestRpc was not included.
Cannot upload crash dump: failed to open
--2022-03-12 17:48:16--  https://sentry.io/api/146342/minidump/?sentry_key=384ce4413de74fe0be270abe03b2b35a
Resolving sentry.io (sentry.io)... 35.188.42.15
Connecting to sentry.io (sentry.io)|35.188.42.15|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-03-12 17:48:18 ERROR 400: Bad Request.


Unexpected crash report id length
Failed to get crash dump id.
Report Id:
[WebContents] double crashed (reason: crashed, exitCode: 139)... RIP =(
```
I also tried running Discord with command `flatpak run com.discordapp.Discord` in both Wayland and Xorg. The behaviour was same in both cases, no windows popped open. 
#### Output:
```
F: Filesystem suffix "ro" is not applicable for --nofilesystem
F: Filesystem suffix "ro" is not applicable for --nofilesystem
Disabling updates already done
[6 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/discord/Discord --type=zygote
Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.9/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
F: Filesystem suffix "ro" is not applicable for --nofilesystem
F: Filesystem suffix "ro" is not applicable for --nofilesystem
Discord 0.0.17
Failed to generate minidump./app/bin/discord: line 18:     6 Segmentation fault      (core dumped) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord $FLAGS "$@"
```

## App information
Running `flatpak info com.discordapp.Discord`:
```
F: Filesystem suffix "ro" is not applicable for --nofilesystem
F: Filesystem suffix "ro" is not applicable for --nofilesystem

Discord - Messaging, Voice, and Video Client

          ID: com.discordapp.Discord
         Ref: app/com.discordapp.Discord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.17
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 197.4 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 957e961bcf20c3d611617c86ba3dbae90d8ffcf8ba1f8a3e095…
      Parent: a22d50c9838dd8d760d8ea3ca3789b1adc7cca030d571d6ed38…
     Subject: Update socat, remove x-checker-data (aca0d62d)
        Date: 2022-02-19 05:42:51 +0000
```

Running `flatpak info --show-permissions com.discordapp.Discord`:
```
F: Filesystem suffix "ro" is not applicable for --nofilesystem
F: Filesystem suffix "ro" is not applicable for --nofilesystem
[Context]
shared=network;ipc;
sockets=pulseaudio;
devices=all;
filesystems=xdg-download;!xdg-pictures;!xdg-videos;

[Session Bus Policy]
org.kde.StatusNotifierWatcher=talk
org.freedesktop.Notifications=talk
com.canonical.AppMenu.Registrar=talk
com.canonical.indicator.application=talk
com.canonical.Unity.LauncherEntry=talk
``` 
## Note
When I install Discord from `pacman` (package manager) it works normally. And I could see Discord in the output of `xlsclients` command. Which, I think, means that it is using Xorg ( `xwayland` is already installed in the system).

## System Information
OS: Manjaro
GNOME Version: 41.3
Windowing System: Wayland

**Comment by TingPing** [comment]
Somebody just needs to update the wrapper script to gracefully handle not being on X11. Was never tested since wayland wasn't supported.

**Comment by TingPing** [comment]
Oh Actually I should have read further. The crash is probably nothing we can do about it. But the script error we can fix.

**Comment by mmarshall540** [comment]
Getting the same traceback on Fedora Silverblue.

**Comment by Sonickyle27** [comment]
I also get this same issue on Arch running KDE Plasma Wayland, but I've also noticed that it also causes Xwayland to stop working completely until reboot. When downgrading the `xorg-xwayland` package to version `21.1.4-1` from `22.0.1-1`, the issue stops occurring and I can open Discord without any issues.

**Comment by TingPing** [comment]
> When downgrading the xorg-xwayland package to version 21.1.4-1 from 22.0.1-1, the issue stops occurring and I can open Discord without any issues.

I'd encourage reporting that upstream to Xorg then.

**Comment by mmarshall540** [comment]
Mea culpa here.

I don't remember changing any of the permissions for this flatpak, but I just used the "Flatseal" app to reset the permissions and the "socket=wayland" toggle switched from on to off. Not sure if anything else was changed.

The app opens and seems to work now.

So if you're seeing that traceback about  `/app/bin/set-gtk-dark-theme.py`, maybe try resetting the flatpak permissions to their defaults and see if that helps.

**Comment by lionirdeadman** [comment]
I'd love to support this feature when we enable Wayland but I'm really not sure how to do that without hardcoding a theme switch.

One other thing that bothers me is that Discord shows a setting to follow the system theme yet it doesn't work.. I'm thinking it might be best to scrap the script altogether and let Discord figure out what they want.

**Comment by neerajlohia** [comment]
Thanks @mmarshall540 
The discord app started working after I did a reset on its permissions using `flatseal`. It changed the toggle on `socket=x11` from off to on. Even I don't remember making changes in the permission, not sure how it got changed.
