### ISSUE TITLE
Issue launching Discord Sway

### ISSUE THREAD

**Issue by CaitlinDavitt** [flathub/com.discordapp.Discord#239]
```
❯ flatpak run com.discordapp.Discord
settings.json doesn't yet exist, can't disable it yet
Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.9/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
Discord 0.0.19
The futex facility returned an unexpected error code.
Failed to generate minidump./app/bin/discord: line 18:     6 Aborted                 (core dumped) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord $FLAGS "$@"
```

**Comment by pedrovanzella** [comment]
Fixed by https://github.com/flathub/com.discordapp.Discord/commit/a040e65269a951bb41a2fc9a060c34c7e00a90cc
