### ISSUE TITLE
python-xlib 0.32 fails because of tkinter import

### ISSUE THREAD

**Issue by jessiehildebrandt** [flathub/com.discordapp.Discord#255]
When launching Discord, the titlebar color is not set because `set-gtk-dark-theme.py` is failing with the message: `ModuleNotFoundError: No module named 'tkinter'`

The app is functional and will still launch, albeit with a light titlebar.

## Logs

```bash
> flatpak run com.discordapp.Discord

Disabling updates already done
[6 zypak-helper] Wait found events, but sd-event found none
Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.10/site-packages/Xlib/display.py", line 120, in __init__
    __import__('Xlib.ext.' + modname)
  File "/app/lib/python3.10/site-packages/Xlib/ext/randr.py", line 37, in <module>
    from tkinter import W
ModuleNotFoundError: No module named 'tkinter'
Discord 0.0.22
```

## System info

openSUSE Tumbleweed
Flatpak 1.14.1

```bash
> flatpak info com.discordapp.Discord 

Discord - Messaging, Voice, and Video Client

          ID: com.discordapp.Discord
         Ref: app/com.discordapp.Discord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.22
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 197.7 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 2ea6028e42af310fc657a3a880dd784ff404753bad63efd9d93e1a5e90789673
      Parent: 9fcdf895a274c10bfd0ab6323fff2668b35c0fa84fb16292c2b070bd494c3623
     Subject: Update URL, URL template and sha256 sum for xprop 1.2.6 (3b56c728)
        Date: 2022-12-10 20:24:25 +0000
```

**Comment by TingPing** [comment]
This is a regression in python-xlib 0.32: https://github.com/python-xlib/python-xlib/commit/c87624dd6ec780417e2d32529976d65fed344045

**Comment by TingPing** [comment]
Issue over it here: https://github.com/python-xlib/python-xlib/issues/240

**Comment by TingPing** [comment]
It will be fixed next update. Will leave this open until upstream fixes it.
