### ISSUE TITLE
Discord won't open link in default browser

### ISSUE THREAD

**Issue by funk443** [flathub/com.discordapp.Discord#277]
I am running Flatpak version of Discord on Void Linux, and it worked all fine in the past.  But when I tried to click a link today, discord just won't open that link in my default browser (firefox.)  Both xdg-open and exo-open works correctly.

I also tried using the tarball from Discord website, and it can open link just fine.  So I am not sure why this is happenning.

Here are the terminal outputs:

```
2023-03-26T08:08:59.809Z [Modules] Modules initializing
2023-03-26T08:08:59.809Z [Modules] Distribution: remote
2023-03-26T08:08:59.809Z [Modules] Host updates: disabled
2023-03-26T08:08:59.810Z [Modules] Module updates: enabled
2023-03-26T08:08:59.810Z [Modules] Module install path: /home/id/.var/app/com.discordapp.Discord/config/discord/0.0.25/modules
2023-03-26T08:08:59.810Z [Modules] Module installed file path: /home/id/.var/app/com.discordapp.Discord/config/discord/0.0.25/modules/installed.json
2023-03-26T08:08:59.810Z [Modules] Module download path: /home/id/.var/app/com.discordapp.Discord/config/discord/0.0.25/modules/pending
2023-03-26T08:08:59.912Z [Modules] No updates to install
2023-03-26T08:08:59.912Z [Modules] Host is up to date.
2023-03-26T08:08:59.912Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
2023-03-26T08:09:00.022Z [Modules] No module updates available.
Optional module ./ElectronTestRpc was not included.
WEIGHT /home/id/.var/app/com.discordapp.Discord/config/discord/0.0.25/modules/discord_krisp/NC_small_8k.thw
WEIGHT /home/id/.var/app/com.discordapp.Discord/config/discord/0.0.25/modules/discord_krisp/NC_small_16k.thw
WEIGHT /home/id/.var/app/com.discordapp.Discord/config/discord/0.0.25/modules/discord_krisp/c6.f.s.ced125.thw
WEIGHT /home/id/.var/app/com.discordapp.Discord/config/discord/0.0.25/modules/discord_krisp/VAD_weight.thw
Error occurred in handler for 'DISCORD_SPELLCHECK_SET_LOCALE': Error: Invalid language code provided: "zh-CN" is not a valid language code
    at /home/id/.var/app/com.discordapp.Discord/config/discord/0.0.25/modules/discord_desktop_core/core.asar/app/discord_native/browser/spellCheck.js:19:35
    at electron/js2c/browser_init.js:201:579
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9805)
    at Object.emit (events.js:315:20)
    at Object.EventEmitter.emit (domain.js:467:12)
2023-03-26T08:09:01.719Z [Modules] Host is up to date.
2023-03-26T08:09:01.719Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
2023-03-26T08:09:01.721Z [Modules] No module updates available.
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.OpenURI? on object at path /org/freedesktop/portal/desktop
```

**Comment by emmandyar** [comment]
have you tried the solution provided in #272 ?

**Comment by funk443** [comment]
> have you tried the solution provided in #272 ?

Yes, I do have xdg-desktop-portal-gtk installed all the time.  Discord could open links before, it stopped working 2 or 3 days ago

**Comment by funk443** [comment]
> it stopped working 2 or 3 days ago

Dang, I am dumb.  Appearently this is what caused the issue.

I updated xdg-desktop-portal-gtk via XBPS to the latest version a few days ago, which supports GNOME 44, and I think this made it incompatible with the one that came with flatpak, thus causing Discord can't open the link in default browser.

Downgrading the xdg-desktop-portal-gtk fixes this issue.

**Comment by mystchonky** [comment]
Is there a way to fix this without using an old version of `xdg-desktop-portal-gtk` ?

**Comment by TingPing** [comment]
@mystchonky Nobody actually found what the issue is. The other comments don't actually make any sense.

This feature is in `xdg-desktop-portal` and `xdg-desktop-portal-gtk` isn't relevant at all.

You should open a new issue and give some more context on your situation. Versions of portals, error messages, etc.

You might just need to set the browser on the host too (`gio mime x-scheme-handler/https`).

**Comment by mystchonky** [comment]
It has automatically started working again! Can confirm this works fine now
